### ISSUE TITLE
An error occurred while listing Conda environments.

### ISSUE THREAD

**Issue by saiogirala** [Anaconda-Platform/nb_conda#85]
An error occurred while listing Conda environments.

![image](https://user-images.githubusercontent.com/47361683/52369716-52062d00-2a1f-11e9-9d6e-45e0b04db372.png)

**Comment by steadyfish** [comment]
I am facing a similar issue. Things worked fine when I opened jupyter notebook for the first time (after  installing nb_conda). I probably installed few other packages after that. Now when I start jupyter notebook, going to "conda" tab results in the error as shown above.

**Comment by dschneiderch** [comment]
I have the same issue on Win 10 Pro 1903

it can't open conda.exe from what I can tell. I tried several of the things mentioned in #23 but nothing helped.
```
jupyter serverextension disable nb_conda
jupyter serverextension enable nb_conda

```
Eventually uninstalled miniconda, deleted my .jupyter/ and .conda and .condarc and started over but that didn't help either.

help!

```
$ jupyter notebook
[E 14:15:49.056 NotebookApp] [nb_conda_kernels] couldn't call conda:
    Command '['C:/Users/dominikschneider/Miniconda3/Scripts/conda.exe', 'info', '--json']' returned non-zero exit status 1.
[I 14:15:49.056 NotebookApp] [nb_conda_kernels] enabled, 0 kernels found
[I 14:15:49.337 NotebookApp] [nb_conda] enabled
[I 14:15:49.337 NotebookApp] Serving notebooks from local directory: C:\Users\dominikschneider\Documents\plantcv
[I 14:15:49.337 NotebookApp] The Jupyter Notebook is running at:
[I 14:15:49.337 NotebookApp] http://localhost:8888/?token=c017e93bc89e8ce68598e0dc8d4b65a6cdf82c2ddc6d3906
[I 14:15:49.337 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:15:49.429 NotebookApp]

```

If I try to run conda.exe I get an unexpected error
```
$ C:/Users/dominikschneider/Miniconda3/Scripts/conda.exe info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\Users\dominikschneider\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "C:\Users\dominikschneider\Miniconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "C:\Users\dominikschneider\Miniconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: LoadLibrary() argument 1 must be str, not None

`$ C:\Users\dominikschneider\Miniconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.
```


Also, anytime I run `conda list` I get an error

```
(plantcv) C:\Users\dominikschneider>conda list

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\core\prefix_data.py", line 130, in iter_records
        return itervalues(self._prefix_records)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\core\prefix_data.py", line 159, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\core\prefix_data.py", line 72, in load
        self._load_site_packages()
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\core\prefix_data.py", line 274, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\gateways\disk\read.py", line 249, in read_python_record
        pydist = PythonDistribution.init(prefix_path, anchor_file, python_version)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 90, in init
        return PythonEggInfoDistribution(anchor_full_path, python_version, sp_reference)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 401, in __init__
        super(PythonEggInfoDistribution, self).__init__(anchor_full_path, python_version)
      File "C:\Users\dominikschneider\Miniconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 104, in __init__
        raise RuntimeError("Path not found: %s" % anchor_full_path)
    RuntimeError: Path not found: C:\Users\dominikschneider\Miniconda3\envs\plantcv\Lib\site-packages\scikit_image-0.14.3-py3.7-win-amd64.egg\EGG-INFO

`$ C:\Users\dominikschneider\Miniconda3\Scripts\conda-script.py list`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=plantcv
                CONDA_EXE=C:\Users\dominikschneider\Miniconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\dominikschneider\Miniconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\Users\dominikschneider\Miniconda3\envs\plantcv
           CONDA_PREFIX_1=C:\Users\dominikschneider\Miniconda3
    CONDA_PROMPT_MODIFIER=(plantcv)
         CONDA_PYTHON_EXE=C:\Users\dominikschneider\Miniconda3\python.exe
               CONDA_ROOT=C:\Users\dominikschneider\Miniconda3
              CONDA_SHLVL=2
                 HOMEPATH=\Users\dominikschneider
          MOZ_PLUGIN_PATH=C:\PROGRAM FILES (X86)\FOXIT SOFTWARE\FOXIT READER\FOXIT
                          READER\plugins\
                     PATH=C:\Users\dominikschneider\Miniconda3;C:\Users\dominikschneider\Minicon
                          da3\Library\mingw-w64\bin;C:\Users\dominikschneider\Miniconda3\Library
                          \usr\bin;C:\Users\dominikschneider\Miniconda3\Library\bin;C:\Users\dom
                          inikschneider\Miniconda3\Scripts;C:\Users\dominikschneider\Miniconda3\
                          bin;C:\Users\dominikschneider\Miniconda3\envs\plantcv;C:\Users\dominik
                          schneider\Miniconda3\envs\plantcv\Library\mingw-w64\bin;C:\Users\domin
                          ikschneider\Miniconda3\envs\plantcv\Library\usr\bin;C:\Users\dominiksc
                          hneider\Miniconda3\envs\plantcv\Library\bin;C:\Users\dominikschneider\
                          Miniconda3\envs\plantcv\Scripts;C:\Users\dominikschneider\Miniconda3\e
                          nvs\plantcv\bin;C:\Users\dominikschneider\Miniconda3\condabin;C:\Progr
                          am Files\Microsoft MPI\Bin;C:\Python27;C:\Python27\Scripts;C:\ProgramD
                          ata\Boxstarter;C:\Rtools\bin;C:\Rtools\mingw_32\bin;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\iCLS;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\iCLS;C:\Windows\syst
                          em32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPo
                          werShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\NVIDIA Corporation\PhysX\Common;C:\Program
                          Files\CMake\bin;C:\Program Files\dcraw;C:\Program Files\nodejs;C:\Prog
                          ramData\chocolatey\bin;C:\Users\dominikschneider\AppData\Local\Program
                          s\orca;C:\Program Files\Microsoft VS Code\bin;C:\Program
                          Files\Pandoc;C:\Program Files\MATLAB\R2019a\bin;C:\WINDOWS\System32\Op
                          enSSH;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDO
                          WS\System32\WindowsPowerShell\v1.0;C:\Users\Dominik
                          Schneider\AppData\Local\atom\bin;C:\Users\Dominik
                          Schneider\AppData\Roaming\npm;C:\Program Files (x86)\Nmap;C:\Users\dom
                          inikschneider\AppData\Local\Microsoft\WindowsApps;C:\Users\dominikschn
                          eider\AppData\Local\GitHubDesktop\bin
             PSMODULEPATH=C:\Users\Dominik Schneider\Documents\WindowsPowerShell\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : plantcv
    active env location : C:\Users\dominikschneider\Miniconda3\envs\plantcv
            shell level : 2
       user config file : C:\Users\dominikschneider\.condarc
 populated config files : C:\Users\dominikschneider\.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\dominikschneider\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/win-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\dominikschneider\Miniconda3\pkgs
                          C:\Users\dominikschneider\.conda\pkgs
                          C:\Users\dominikschneider\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\dominikschneider\Miniconda3\envs
                          C:\Users\dominikschneider\.conda\envs
                          C:\Users\dominikschneider\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by flysoulbird** [comment]
![image](https://user-images.githubusercontent.com/65176299/82194727-d71e0880-9929-11ea-80cf-987b7095dccb.png)

reinstall the lastest nb_conda version,solve the question,
but another question coming
![image](https://user-images.githubusercontent.com/65176299/82194672-c2417500-9929-11ea-9143-a4d29d8d7eb6.png)

modify the file to solve the question  C:\Users\<user>\anaconda3\pkgs\nb_conda-2.2.1-py37_0\Lib\site-packages\nb_conda\envmanager.py,
find:
![{T8ID )I0WURYR{8XJ7 PX0](https://user-images.githubusercontent.com/65176299/82195325-ba360500-992a-11ea-9300-e9cba2881ff4.png)
modify:
![8HQ24I09364O{B8WCIXANFU](https://user-images.githubusercontent.com/65176299/82195390-d5087980-992a-11ea-8ea4-b6b09111ad16.png)
Restart jupyter notebook server and the error prompt disappears.

**Comment by LalliBlan** [comment]
It worked!!! Thanks!!!

**Comment by yinfeng242** [comment]
that's great!  the problem was solved!
